// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Infrastructure.Data;

#nullable disable

namespace TaskManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 10, 15, 22, 25, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa pendente.",
                            Status = 0,
                            Titulo = "Teste 01 - Tarefa Pendente"
                        },
                        new
                        {
                            Id = 2,
                            DataConclusao = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2025, 10, 15, 15, 21, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa concluida.",
                            Status = 2,
                            Titulo = "Teste 02 - Tarefa Concluída"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 10, 15, 18, 36, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa em andamento.",
                            Status = 1,
                            Titulo = "Teste 03 - Em Andamento"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 10, 15, 12, 25, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa pendente.",
                            Status = 0,
                            Titulo = "Teste 04 - Prioridade Alta"
                        },
                        new
                        {
                            Id = 5,
                            DataConclusao = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2025, 10, 15, 9, 25, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa concluida.",
                            Status = 2,
                            Titulo = "Teste 05 - Concluído Hoje"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 10, 15, 10, 25, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa em andamento.",
                            Status = 1,
                            Titulo = "Teste 06 - Desenvolvimento"
                        },
                        new
                        {
                            Id = 7,
                            DataCriacao = new DateTime(2025, 10, 15, 11, 25, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa pendente.",
                            Status = 0,
                            Titulo = "Teste 07 - Revisão de Código"
                        },
                        new
                        {
                            Id = 8,
                            DataCriacao = new DateTime(2025, 10, 15, 11, 34, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa pendente.",
                            Status = 0,
                            Titulo = "Teste 08 - Tarefa Urgente"
                        },
                        new
                        {
                            Id = 9,
                            DataConclusao = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2025, 10, 15, 22, 11, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa concluida.",
                            Status = 2,
                            Titulo = "Teste 09 - Antiga Concluída"
                        },
                        new
                        {
                            Id = 10,
                            DataCriacao = new DateTime(2025, 10, 15, 15, 1, 31, 0, DateTimeKind.Utc),
                            Descricao = "Descrição detalhada da tarefa em andamento.",
                            Status = 1,
                            Titulo = "Teste 10 - Documentação"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
